# This file was generated by GoReleaser. DO NOT EDIT.
cask "llama-tui" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "04455c05a7407fb13227cd1a2eb3fdd8d06587c09d788132de5b2602c8817b1d"
      url "https://github.com/AresiusXP/llama-tui/releases/download/v#{version}/llama-tui_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/AresiusXP/llama-tui/"
    end
    on_arm do
      sha256 "4198e4f935425c085ced3ffc73476790fa2b8fa49b87f152ddb64efc273e58c8"
      url "https://github.com/AresiusXP/llama-tui/releases/download/v#{version}/llama-tui_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/AresiusXP/llama-tui/"
    end
  end

  on_linux do
    on_intel do
      sha256 "3f60b2b80b64094c1e0aa1b03b384e7dbdc0011307ebd0d9dbf77d9b668bcb50"
      url "https://github.com/AresiusXP/llama-tui/releases/download/v#{version}/llama-tui_#{version}_linux_amd64.tar.gz",
        verified: "github.com/AresiusXP/llama-tui/"
    end
    on_arm do
      sha256 "ad1869b0673326e2b73092ca530afec040d3d82dee42046e8969ebeba9dcc537"
      url "https://github.com/AresiusXP/llama-tui/releases/download/v#{version}/llama-tui_#{version}_linux_arm64.tar.gz",
        verified: "github.com/AresiusXP/llama-tui/"
    end
  end

  name "llama-tui"
  desc "A TUI for managing and running local LLM models via llama-server"
  homepage "https://github.com/AresiusXP/llama-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llama-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/llama-tui"]
    end
  end

  # No zap stanza required

end
