# This file was generated by GoReleaser. DO NOT EDIT.
cask "llama-tui" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "952c67c49f0681ea8eb5728e801b9fc66244c2b780d12ab2375804aa2f07b762"
      url "https://github.com/AresiusXP/llama-tui/releases/download/v#{version}/llama-tui_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/AresiusXP/llama-tui/"
    end
    on_arm do
      sha256 "5d8c16b84e4cd4867710d270d623467b0e18a808b27598fdaa505ed475376f64"
      url "https://github.com/AresiusXP/llama-tui/releases/download/v#{version}/llama-tui_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/AresiusXP/llama-tui/"
    end
  end

  on_linux do
    on_intel do
      sha256 "127134db3a6a29c4dcf8efc1176b8a5339535be75a51d23b31277c473f579b47"
      url "https://github.com/AresiusXP/llama-tui/releases/download/v#{version}/llama-tui_#{version}_linux_amd64.tar.gz",
        verified: "github.com/AresiusXP/llama-tui/"
    end
    on_arm do
      sha256 "e1cf21cab5cce24dffe405d1797f82044af9cad07a3c8ae5746c0b080db1e8b0"
      url "https://github.com/AresiusXP/llama-tui/releases/download/v#{version}/llama-tui_#{version}_linux_arm64.tar.gz",
        verified: "github.com/AresiusXP/llama-tui/"
    end
  end

  name "llama-tui"
  desc "A TUI for managing and running local LLM models via llama-server"
  homepage "https://github.com/AresiusXP/llama-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llama-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/llama-tui"]
    end
  end

  # No zap stanza required

end
