# This file was generated by GoReleaser. DO NOT EDIT.
cask "llama-tui" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "0d810890b3984e5fd3329620041bdb2ca09c05cdabaf328e2a412f6faf17e358"
      url "https://github.com/AresiusXP/llama-tui/releases/download/v#{version}/llama-tui_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/AresiusXP/llama-tui/"
    end
    on_arm do
      sha256 "9d463492b1111291952c4ddb51fa613f62e10fad693d9dd882f41e8be16e62b5"
      url "https://github.com/AresiusXP/llama-tui/releases/download/v#{version}/llama-tui_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/AresiusXP/llama-tui/"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c099b4776a9b6b659b908de78ccdc10bf0367e0ee725fb10e9da303e53b0449"
      url "https://github.com/AresiusXP/llama-tui/releases/download/v#{version}/llama-tui_#{version}_linux_amd64.tar.gz",
        verified: "github.com/AresiusXP/llama-tui/"
    end
    on_arm do
      sha256 "1c653964469215901b63464c07d5bdc3ad05c46b32dcf727d8a334ae424e7d25"
      url "https://github.com/AresiusXP/llama-tui/releases/download/v#{version}/llama-tui_#{version}_linux_arm64.tar.gz",
        verified: "github.com/AresiusXP/llama-tui/"
    end
  end

  name "llama-tui"
  desc "A TUI for managing and running local LLM models via llama-server"
  homepage "https://github.com/AresiusXP/llama-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llama-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/llama-tui"]
    end
  end

  # No zap stanza required

end
